name: shared
description: "Shared code (as package) for the Flutter Full-Stack Todo App's Back-End & Front-End."
version: 1.0.0
homepage:

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  build_runner: ^2.9.0
  json_annotation: ^4.9.0
  json_serializable: ^6.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
