name: backend_dart_frog
description: The back-end side for the full stack Flutter Todo App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  shared: 1.0.0 # the shared code (pkg)
  dart_frog: ^1.1.0
  postgres: ^3.5.7
  bcrypt: ^1.1.3
  dart_jsonwebtoken: ^3.3.1
  dart_frog_auth: ^1.2.2
  dotenv: ^4.2.0

dev_dependencies:
  dart_frog_lint: ^0.1.0
  mocktail: ^1.0.3
  test: ^1.25.5
